services:
  - type: web
    name: jd-analyzer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:@Cursor2025@db.awlfgubnleuhudvnimxp.supabase.co:5432/postgres
      - key: HUGGINGFACE_API_KEY
        value: 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
      - key: JWT_SECRET
        value: jd_analyzer_secret_key_2024
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        value: https://intassist.vercel.app 