services:
  - type: web
    name: jd-analyzer-backend
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        value: https://intassist.vercel.app
      - key: PYTHONUNBUFFERED
        value: 1 